version: "3.8"
services:
  builder:
    image: ubuntu:20.04
    build:
      context: .
      dockerfile: ./docker/docker-builder
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ["sh", "/usr/src/app/docker/scripts/startup.sh"]
    environment:
      CERT_REPORT_FILENAME: ${CERT_REPORT_FILENAME}
