services:
  odata-manager-app:
    restart: on-failure
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE
      - MONGO_SYNC_CONNECTION_STR
      - MONGO_DATABASE
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_URL
      - ENABLE_DEBUG=false
      - LOOKUP_TYPE
      - CERT_REPORT_FILENAME
    volumes:
      - ./build/libs:/usr/local/tomcat/webapps
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mariadb:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${MYSQL_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Development Tools
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo-db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGO_SYNC_CONNECTION_STR}
      ME_CONFIG_BASICAUTH: false

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8082:80"

volumes:
  mysql_data:
  mongo_data: